### ISSUE TITLE
Invalid credentials, or perhaps something else?

### ISSUE THREAD

**Issue by jwest31337** [AlertPageSDR/tr_configurator#5]
I can't seem to get this to run, despite manually validating my credentials. I'm not sure if I'm supplying the command line options incorrectly, or if something else is going on.

:~/tr_configurator$ **./main.py -s 3783:15878 -u jwest31337 -p MyPassHere -r --talkgroups**

_CRITICAL:root:[!] Invalid Radio Reference Username or Password
Traceback (most recent call last):
  File "/home/jwest/tr_configurator/./main.py", line 612, in <module>
    main()
  File "/home/jwest/tr_configurator/./main.py", line 546, in main
    for system in SYSTEM_RESULTS:
                  ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'SYSTEM_RESULTS' where it is not associated with a value_

Running Python 3.11.2 with zeep installed. Any idea what I'm doing wrong here? Many thanks in advance!

**Comment by rdmcvicar** [comment]
I'd been meaning to play with this handy tool some more, as I spend a bit of time writing and otherwise dealing with these files on a number of systems and sites.

I pasted (editing in my own RR creds) your command and ran it (Python 3.10.12) -- seemingly successfully.  So the message about an issue with the RR username or password seem consistent with that.  I'm struggling to think of ideas.  Might you have a password containing a character that causes unhappiness when mentioned on the command line (I don't even know if this is a thing; just tossing it out there)?

Here's the config.json file (If you have an immediate need for the csv file, too -- just let me know):

{
    "ver": 2,
    "sources": [
        {
            "center": 151008125,
            "rate": 3001256,
            "ppm": 0,
            "gain": 49,
            "agc": false,
            "digitalRecorders": 3,
            "analogRecorders": 0,
            "driver": "osmosdr",
            "device": "rtl=0"
        },
        {
            "center": 152761875,
            "rate": 900000,
            "ppm": 0,
            "gain": 49,
            "agc": false,
            "digitalRecorders": 2,
            "analogRecorders": 0,
            "driver": "osmosdr",
            "device": "rtl=1"
        },
        {
            "center": 159431875,
            "rate": 900000,
            "ppm": 0,
            "gain": 49,
            "agc": false,
            "digitalRecorders": 1,
            "analogRecorders": 0,
            "driver": "osmosdr",
            "device": "rtl=2"
        }
    ],
    "systems": [
        {
            "control_channels": [
                152802500,
                152502500
            ],
            "type": "p25",
            "digitalLevels": 1,
            "talkgroupsFile": "",
            "shortName": "",
            "modulation": "fsk4",
            "hideEncrypted": false,
            "uploadScript": "",
            "talkgroupDisplayFormat": "id_tag",
            "compressWav": false,
            "rrsysid": "3783",
            "rrsiteid": "15878"
        }
    ],
    "captureDir": "",
    "logLevel": "info",
    "broadcastSignals": true,
    "frequencyFormat": "mhz",
    "logFile": true

**Comment by jwest31337** [comment]
Hello rdmcvicar,

Thanks for getting back to me and doing some testing, I greatly appreciate it. I did consider that my username/password contained invalid characters, so I changed them to something very simple on RR's site, and re-tested, but no luck. Do either the user/pass have to be encapsulated in quotations or anything special when plugging them in from the command line?

The only other thing I can think of is that I'm running Python on a 32 bit system, and I don't think I was running it from a Virtual Environment. I was just calling main.py directly. Do you think that would affect anything? Thanks again for any suggestions. I can also try to test it from a different Linux install if you think that might be successful.

**Comment by kcwebby** [comment]
This feature does require you to be a premium subscriber, or feed provider.   I thought I commented on this question months ago, but cannot find it, apologies for that

**Comment by jwest31337** [comment]
Ah thank you very much for mentioning that. I picked up a premium subscription and re-tested it, and everything works perfectly. I greatly appreciate your testing and time.
